[2024-05-18T06:41:12.588+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: temp_humi_dag.fetch_data_from_api scheduled__2024-05-17T00:00:00+00:00 [queued]>
[2024-05-18T06:41:12.617+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: temp_humi_dag.fetch_data_from_api scheduled__2024-05-17T00:00:00+00:00 [queued]>
[2024-05-18T06:41:12.620+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2024-05-18T06:41:12.639+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_data_from_api> on 2024-05-17 00:00:00+00:00
[2024-05-18T06:41:12.644+0000] {standard_task_runner.py:60} INFO - Started process 551 to run task
[2024-05-18T06:41:12.647+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'temp_humi_dag', 'fetch_data_from_api', 'scheduled__2024-05-17T00:00:00+00:00', '--job-id', '390', '--raw', '--subdir', 'DAGS_FOLDER/ICTTemp_Humi_DAG.py', '--cfg-path', '/tmp/tmpp_5g5waa']
[2024-05-18T06:41:12.651+0000] {standard_task_runner.py:88} INFO - Job 390: Subtask fetch_data_from_api
[2024-05-18T06:41:12.716+0000] {task_command.py:423} INFO - Running <TaskInstance: temp_humi_dag.fetch_data_from_api scheduled__2024-05-17T00:00:00+00:00 [running]> on host e3e2dc6bc2be
[2024-05-18T06:41:12.820+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Group4' AIRFLOW_CTX_DAG_ID='temp_humi_dag' AIRFLOW_CTX_TASK_ID='fetch_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T00:00:00+00:00'
[2024-05-18T06:41:15.917+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-05-18T06:41:15.926+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=temp_humi_dag, task_id=fetch_data_from_api, execution_date=20240517T000000, start_date=20240518T064112, end_date=20240518T064115
[2024-05-18T06:41:15.962+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-18T06:41:15.991+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
