[2024-05-17T09:59:18.611+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_data_attendance.delete_att_data_into_db manual__2024-05-17T09:59:15.636720+00:00 [queued]>
[2024-05-17T09:59:18.617+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_data_attendance.delete_att_data_into_db manual__2024-05-17T09:59:15.636720+00:00 [queued]>
[2024-05-17T09:59:18.618+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2024-05-17T09:59:18.625+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): delete_att_data_into_db> on 2024-05-17 09:59:15.636720+00:00
[2024-05-17T09:59:18.629+0000] {standard_task_runner.py:60} INFO - Started process 1828 to run task
[2024-05-17T09:59:18.631+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'api_data_attendance', 'delete_att_data_into_db', 'manual__2024-05-17T09:59:15.636720+00:00', '--job-id', '298', '--raw', '--subdir', 'DAGS_FOLDER/api_data_attendance.py', '--cfg-path', '/tmp/tmpgb5zprrk']
[2024-05-17T09:59:18.633+0000] {standard_task_runner.py:88} INFO - Job 298: Subtask delete_att_data_into_db
[2024-05-17T09:59:18.661+0000] {task_command.py:423} INFO - Running <TaskInstance: api_data_attendance.delete_att_data_into_db manual__2024-05-17T09:59:15.636720+00:00 [running]> on host e3e2dc6bc2be
[2024-05-17T09:59:18.703+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_data_attendance' AIRFLOW_CTX_TASK_ID='delete_att_data_into_db' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T09:59:15.636720+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-17T09:59:15.636720+00:00'
[2024-05-17T09:59:18.709+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-05-17T09:59:18.722+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-05-17T09:59:18.730+0000] {sql.py:450} INFO - Running statement: 
        DELETE FROM attendance;
        , parameters: None
[2024-05-17T09:59:18.733+0000] {sql.py:459} INFO - Rows affected: 0
[2024-05-17T09:59:18.735+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-05-17T09:59:18.742+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=api_data_attendance, task_id=delete_att_data_into_db, execution_date=20240517T095915, start_date=20240517T095918, end_date=20240517T095918
[2024-05-17T09:59:18.763+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-17T09:59:18.778+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
